apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: bpf-pacchetti-bpf
  name: bpf-pacchetti-bpf
  namespace: default
spec:
  endpoints:
  - path: /metrics
    port: bpf
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: bpf-pacchetti-bpf
